version: '3'

networks:
  docker:
    driver: bridge

volumes:
  postgres:


services:
  service-account:
    build:
      context: .
      dockerfile: ./apps/service-account/Dockerfile
      # target: development
      target: production
    env_file:
      - ./apps/service-account/.env.local
    network_mode: host
    ports:
      - '4000:4000'
