version: '3'

networks:
  docker:
    driver: bridge

volumes:
  postgres:


services:
  service-account:
    build:
      context: .
      dockerfile: ./apps/service-account/Dockerfile
      target: development
    environment:
      PORT: 4000
      PRIMARY_DB_HOST: postgres
      PRIMARY_DB_PORT: 5432
      PRIMARY_DB_USERNAME: postgres
      PRIMARY_DB_PASSWORD: postgres
      PRIMARY_DB_DATABASE: postgres
    ports:
      - '4000:4000'
    depends_on:
      - postgres

  postgres:
    image: bitnami/postgresql
    deploy:
      mode: global
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_DATABASE: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres:/bitnami/postgresql
